kind: Secret
apiVersion: v1
metadata:
  annotations:
  name: catalog-database
  labels:
data:
  database-name: Y2F0YWxvZw==
  database-password: bXlzZWNyZXRwYXNzd29yZA==
  database-user: Y2F0YWxvZw==
type: Opaque
