apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coolstore
resources:
- coolstore-ns.yaml
- cart-dc.yaml
- coolstore-ui-dc.yaml
- inventorydb-secret.yaml
- cart-is.yaml
- coolstore-ui-is.yaml
- inventorydb-service.yaml
- cart-route.yaml
- coolstore-ui-route.yaml
- cart-service.yaml
- coolstore-ui-service.yaml
- order-dc.yaml
- catalog-dc.yaml
- datagrid-dc.yaml
- order-is.yaml
- catalog-is.yaml
- datagrid-is.yaml
- order-route.yaml
- catalog-route.yaml
- datagrid-service.yaml
- order-service.yaml
- catalog-service.yaml
- inventory-dc.yaml
- orderdb-dc.yaml
- catalogdb-dc.yaml
- inventory-is.yaml
- orderdb-is.yaml
- catalogdb-secret.yaml
- inventory-route.yaml
- orderdb-service.yaml
- catalogdb-service.yaml
- inventory-service.yaml
- coolstore-ns.yaml
- inventorydb-dc.yaml
