kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
  name: catalog
  labels:
    app: catalog
    app.kubernetes.io/component: catalog
    app.kubernetes.io/instance: catalog
    app.kubernetes.io/part-of: catalog
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations:
        openshift.io/imported-from: 'quay.io/ramgopireddy/catalog:latest'
      from:
        kind: DockerImage
        name: 'quay.io/ramgopireddy/catalog:latest'
      generation: 2
      importPolicy: {}
      referencePolicy:
        type: Source
