kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
  name: datagrid-service
  labels:
    app: datagrid-service
    app.kubernetes.io/component: datagrid-service
    app.kubernetes.io/instance: datagrid-service
spec:
  lookupPolicy:
    local: false
  tags:
    - name: 12.0.0.Final-1
      annotations:
        openshift.io/imported-from: 'infinispan/server:12.0.0.Final-1'
      from:
        kind: DockerImage
        name: 'infinispan/server:12.0.0.Final-1'
      generation: 2
      importPolicy: {}
      referencePolicy:
        type: Source
