kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
  name: inventory
  labels:
    app: inventory
    app.kubernetes.io/component: inventory
    app.kubernetes.io/instance: inventory
    app.kubernetes.io/part-of: inventory
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations:
        openshift.io/imported-from: 'quay.io/ramgopireddy/inventory:latest'
      from:
        kind: DockerImage
        name: 'quay.io/ramgopireddy/inventory:latest'
      generation: 2
      importPolicy: {}
      referencePolicy:
        type: Source
