kind: Secret
apiVersion: v1
metadata:
  annotations:
  name: inventory-database
  labels:
data:
  database-name: aW52ZW50b3J5
  database-password: bXlzZWNyZXRwYXNzd29yZA==
  database-user: aW52ZW50b3J5
type: Opaque
